### PR TITLE
updated german translations

### PR DESCRIPTION
**Pull request by JackOBIsReal**
…ified in-game or on eso-hub for those sets not showing up in the set overview.

### CODE REVIEW

**Comment by Baertram** [comment]
Hi there, I'm confused? The set names "ingame" come from the ingame API. The excel file won't change any ingame data of the names.
The setNames in the excel file are just there to find them in the excel and I have even removed German translations at most rows as it was a mess to update English and German.

So what "set names" did you change in the excel then? Could you briefly explain as there is no comparison for binary files like the excel is within GitHub.
I do not see any need to import a pull request for German data here unless it's e.g. the drop location and Boss names in German maybe?

**Review by Baertram — COMMENTED** [review]
Hi there, I'm confused? The set names "ingame" come from the ingame API. The excel file won't change any ingame data of the names.
The setNames in the excel file are just there to find them in the excel and I have even removed German translations at most rows as it was a mess to update English and German.

So what "set names" did you change in the excel then? Could you briefly explain as there is no comparison for binary files like the excel is within GitHub.
I do not see any need to import a pull request for German data here unless it's e.g. the drop location and Boss names in German maybe?

**Comment by JackOBIsReal** [comment]
ah ok, I thought that was meant as an in Library way of getting the name.

**Comment by Baertram** [comment]
Hi, it is, but it gets the names straight from the ingame API functions and I put those simply in the preloaded data lua file. The excel is just for building the needed data as lua code, and all data comes from the game API, not the excel ;-)

Sorry that you took the time to update all the info but this won't affect anything ingame.
Changing German names or any other language in the excel won't change anything ingame EXCEPT for the drop type/locations (like dropped by boss with name "Selene"). Those are manually added and the German translations could be changed if they are wrong.


If you got an example ingame where the LibSets API functions like LibSets.GetSetName(setId) return wrong values (e.g. English if it should return German) please tell me the setId and the API function used and I'll have a look.
So far all the preloaded data looks okay to me though.

**Pull request closed without merging**
